name: evidence sync
on:
    push:
        branches:
            - main
jobs:
    detect-changes:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 2

            - name: Print modified files
              run: | 
                echo "modified files: " 
                git diff --diff-filter=M --name-only HEAD~1 HEAD -- frontend/ backend/
                |



